version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend/rails/achievelist:/achievelist
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "80:3000"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/react/achievelist:/usr/src/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
volumes:
  db_data: